name       : openmsx
version    : 0.15.0
release    : 9
source     :
    - https://github.com/openMSX/openMSX/archive/RELEASE_0_15_0.tar.gz : 452b0189899abd99e921a084ce2800cdb678e09de7584ffabacab1576d66c911
license    : GPL-2.0-or-later
component  : games.emulator
summary    : openMSX is an emulator for the MSX home computer system
description: |
    openMSX is an emulator for the MSX home computer system
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(SDL_ttf)
    - pkgconfig(tcl)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
setup      : |
    sed -i 's@INSTALL_BASE:=/opt/openMSX@INSTALL_BASE:=/usr/share/openmsx@' build/custom.mk
    echo 'INSTALL_DOC_DIR:=/usr/share/doc/openmsx' >> build/custom.mk
    echo 'INSTALL_SHARE_DIR:=/usr/share/openmsx' >> build/custom.mk
    echo 'INSTALL_BINARY_DIR:=/usr/bin' >> build/custom.mk
    %configure
build      : |
    %make
install    : |
    %make_install
