name       : openmsx
version    : 0.13.0
release    : 1
source     :
    - https://github.com/openMSX/openMSX/releases/download/RELEASE_0_13_0/openmsx-0.13.0.tar.gz : 41e37c938be6fc9f90659f8808418133601a85475058725d3e0dccf2902e62cb
license    : GPL-2.0
component  : games.emulator
summary    : openMSX is an emulator for the MSX home computer system
description: |
    openMSX is an emulator for the MSX home computer system
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(SDL_ttf)
    - pkgconfig(tcl)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
setup      : |
    sed -i 's@INSTALL_BASE:=/opt/openMSX@INSTALL_BASE:=/usr/share/openmsx@' build/custom.mk
    echo 'INSTALL_DOC_DIR:=/usr/share/doc/openmsx' >> build/custom.mk
    echo 'INSTALL_SHARE_DIR:=/usr/share/openmsx' >> build/custom.mk
    echo 'INSTALL_BINARY_DIR:=/usr/bin' >> build/custom.mk
    %configure
build      : |
    %make
install    : |
    %make_install
